# Network Expansion
# Model 1 - Deterministic Baseline

In [1]:
import os 
os.chdir("..")

In [2]:
import numpy as np
import pandas as pd
from src.classes import DistributionNetwork
from src.classes import Substation

![Topology example](../figures/topology_example.png)  
*Example topology of a distribution system evaluated in this notebook.*

Defining the Distribution Network: Input data

In [3]:
NODES = [f"N{i}" for i in range(1,17)] # Listing system nodes: 'N1','N2', ..., 'N16'
LOADS = [f'D{i}' for i in range(1,11)] # Listing system loads: 'D1', 'D2', ..., 'D10'
SUBSTATIONS = ['S1'] # Initial substations
substation_capacity = {'S1': 40}
load_capacity = {'D1': 5,
                 'D2': 2,
                 'D3': 2,
                 'D4': 5,
                 'D5': 3,
                 'D6': 2,
                 'D7': 6,
                 'D8': 5,
                 'D9': 3,
                 'D10': 4}

Mapping (nodal locations)

In [4]:
# Substations
mapping_substations = pd.DataFrame(0, index=SUBSTATIONS, columns=NODES)
mapping_substations.loc['S1', 'N4'] = 1
mapping_substations

    N1  N2  N3  N4  N5  N6  N7  N8  N9  N10  N11  N12  N13  N14  N15  N16
S1   0   0   0   1   0   0   0   0   0    0    0    0    0    0    0    0

In [5]:
# Loads
mapping_loads = pd.DataFrame(0, index=LOADS, columns=NODES)
loads_locations = {
    "D1": "N1",
    "D2": "N2",
    "D3": "N3",
    "D4": "N6",
    "D5": "N7",
    "D6": "N8",
    "D7": "N9",
    "D8": "N11",
    "D9": "N12",
    "D10": "N13",
}

for load, node in loads_locations.items():
    mapping_loads.loc[load, node] = 1

mapping_loads

     N1  N2  N3  N4  N5  N6  N7  N8  N9  N10  N11  N12  N13  N14  N15  N16
D1    1   0   0   0   0   0   0   0   0    0    0    0    0    0    0    0
D2    0   1   0   0   0   0   0   0   0    0    0    0    0    0    0    0
D3    0   0   1   0   0   0   0   0   0    0    0    0    0    0    0    0
D4    0   0   0   0   0   1   0   0   0    0    0    0    0    0    0    0
D5    0   0   0   0   0   0   1   0   0    0    0    0    0    0    0    0
D6    0   0   0   0   0   0   0   1   0    0    0    0    0    0    0    0
D7    0   0   0   0   0   0   0   0   1    0    0    0    0    0    0    0
D8    0   0   0   0   0   0   0   0   0    0    1    0    0    0    0    0
D9    0   0   0   0   0   0   0   0   0    0    0    1    0    0    0    0
D10   0   0   0   0   0   0   0   0   0    0    0    0    1    0    0    0

In [6]:
# Distribution lines (arcs)
mapping_lines = pd.DataFrame(0, index=NODES, columns=NODES)
nodes_connected = {
    "N1": ["N2"],
    "N2": ["N1", "N3"],
    "N3": ["N2", "N4"],
    "N4": ["N3", "N5", "N9"],
    "N5": ["N4", "N6"],
    "N6": ["N5","N7", "N8"],
    "N7": ["N6"],
    "N8": ["N6"],
    "N9": ["N4", "N10", "N11", "N13"],
    "N10": ["N9"],
    "N11": ["N9", "N12"],
    "N12": ["N11"],
    "N13": ["N9"]
}

for node, nodes in nodes_connected.items():
    mapping_lines.loc[node, nodes] = 1

mapping_lines

     N1  N2  N3  N4  N5  N6  N7  N8  N9  N10  N11  N12  N13  N14  N15  N16
N1    0   1   0   0   0   0   0   0   0    0    0    0    0    0    0    0
N2    1   0   1   0   0   0   0   0   0    0    0    0    0    0    0    0
N3    0   1   0   1   0   0   0   0   0    0    0    0    0    0    0    0
N4    0   0   1   0   1   0   0   0   1    0    0    0    0    0    0    0
N5    0   0   0   1   0   1   0   0   0    0    0    0    0    0    0    0
N6    0   0   0   0   1   0   1   1   0    0    0    0    0    0    0    0
N7    0   0   0   0   0   1   0   0   0    0    0    0    0    0    0    0
N8    0   0   0   0   0   1   0   0   0    0    0    0    0    0    0    0
N9    0   0   0   1   0   0   0   0   0    1    1    0    1    0    0    0
N10   0   0   0   0   0   0   0   0   1    0    0    0    0    0    0    0
N11   0   0   0   0   0   0   0   0   1    0    0    1    0    0    0    0
N12   0   0   0   0   0   0   0   0   0    0    1    0    0    0    0    0
N13   0   0   0   0   0   0   0   0   1    0    0    0    0    0    0    0
N14   0   0   0   0   0   0   0   0   0    0    0    0    0    0    0    0
N15   0   0   0   0   0   0   0   0   0    0    0    0    0    0    0    0
N16   0   0   0   0   0   0   0   0   0    0    0    0    0    0    0    0

Instancing a pre-defined Distribution Network

In [7]:
DistributionNetwork = DistributionNetwork(NODES, 
                                          LOADS, 
                                          SUBSTATIONS, 
                                          load_capacity, 
                                          substation_capacity, 
                                          mapping_lines,
                                          mapping_loads,
                                          mapping_substations)

In [8]:
# TODO: (optional) Draw current Distribution Network

Adding *candidate* substations for expansion (with potential connection lines)

In [9]:
capacity = 40 # MVA
S2 = Substation("S2", "N14", capacity, ["N2"]) # Potential substation S2 at node N14, with potential connection to node N2
S3 = Substation("S3", "N15", capacity, ["N5"])
S4 = Substation("S4", "N16", capacity, ["N11", "N13"])
DistributionNetwork.add_candidate_substations([S2, S3, S4])

Defining a Network Expansion optimization problem

1. Objective function
2. Input data
3. Decision variables
4. Constraints

In [10]:
# TODO:

Solving the optimization problem  
- single-time x 10 years (with consequent Distribution Networks as new inputs)

In [11]:
# TODO:

Results, plots, short insights

In [12]:
# TODO:

![Final example](../figures/final_example.png)  
*Hypothetical optimization solution.*  
// Just to illustrate network behavior